spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/social_feed?serverTimezone=Asia/Seoul
    username: root
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  data:
    redis:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
      host: ${REDIS_HOST}
      port: 15250
      password: ${PASSWORD}
      username: Default

jwt:
  key: ${JWT_KEY}